packages:
  - "packages/*"
  - "apps/*"

catalog:
  ajv: "^8.17.1"
  vite: "6.0.11"
  vitest: "3.0.4"
  svelte: "^5.18.0"
  "@sveltejs/kit": "^2.15.3"
  "@sveltejs/adapter-static": "^3.0.8"
  "@sveltejs/package": "^2.3.7"
  "@sveltejs/vite-plugin-svelte": "^5.0.3"
  svelte-check: "^4.1.3"
  "@tsconfig/svelte": "^5.0.4"
  "@playwright/test": "^1.49.1"
  "@types/eslint": "^9.6.1"
  "autoprefixer": "^10.4.20"
  "eslint": "^9.17.0"
  "eslint-config-prettier": "^9.1.0"
  "eslint-plugin-svelte": "^2.46.1"
  "globals": "^15.14.0"
  "postcss": "^8.4.49"
  "prettier": "^3.4.2"
  "prettier-plugin-svelte": "^3.3.2"
  "tailwindcss": "^3.4.17"
  "typescript-eslint": "^8.19.1"
  "zod": "^3.24.1"
  "@tailwindcss/vite": "^4.0.3"

catalogs:
  next:
    "tailwindcss": "^4.0.3"