packages:
  - "packages/*"
  - "apps/*"

catalog:
  "ajv": "^8.17.1"
  "vite": "6.3.5"
  "svelte": "^5.30.2"
  "esm-env": "^1.2.2"
  "@sveltejs/kit": "^2.21.1"
  "@sveltejs/adapter-static": "^3.0.8"
  "@sveltejs/package": "^2.3.11"
  "@sveltejs/vite-plugin-svelte": "^5.0.3"
  "svelte-check": "^4.2.1"
  "@tsconfig/svelte": "^5.0.4"
  "@playwright/test": "^1.52.0"
  "@types/eslint": "^9.6.1"
  "autoprefixer": "^10.4.21"
  "eslint": "^9.27.0"
  "eslint-config-prettier": "^10.1.5"
  "eslint-plugin-svelte": "^3.8.1"
  "@eslint/compat": "^1.2.9"
  "@eslint/js": "^9.27.0"
  "globals": "^16.1.0"
  "postcss": "^8.5.3"
  "prettier": "^3.5.3"
  "prettier-plugin-svelte": "^3.4.0"
  "prettier-plugin-tailwindcss": "^0.6.11"
  "tailwindcss": "^3.4.17"
  "typescript-eslint": "^8.32.1"
  "zod": "^3.24.4"
  "@tailwindcss/vite": "^4.1.7"
  "@exodus/schemasafe": "^1.3.0"
  "@testing-library/svelte": "^5.2.7"
  "@testing-library/jest-dom": "^6.6.3"

catalogs:
  next:
    "tailwindcss": "^4.1.7"