packages:
  - "packages/*"
  - "apps/*"

catalog:
  "ajv": "^8.17.1"
  "vite": "6.2.1"
  "vitest": "3.0.8"
  "svelte": "^5.22.6"
  "esm-env": "^1.2.2"
  "@sveltejs/kit": "^2.19.0"
  "@sveltejs/adapter-static": "^3.0.8"
  "@sveltejs/package": "^2.3.10"
  "@sveltejs/vite-plugin-svelte": "^5.0.3"
  "svelte-check": "^4.1.4"
  "@tsconfig/svelte": "^5.0.4"
  "@playwright/test": "^1.50.1"
  "@types/eslint": "^9.6.1"
  "autoprefixer": "^10.4.20"
  "eslint": "^9.21.0"
  "eslint-config-prettier": "^10.0.2"
  "eslint-plugin-svelte": "^3.0.3"
  "globals": "^16.0.0"
  "postcss": "^8.5.3"
  "prettier": "^3.5.3"
  "prettier-plugin-svelte": "^3.3.3"
  "tailwindcss": "^3.4.17"
  "typescript-eslint": "^8.26.0"
  "zod": "^3.24.2"
  "@tailwindcss/vite": "^4.0.11"

catalogs:
  next:
    "tailwindcss": "^4.0.11"