packages:
  - "packages/*"
  - "apps/*"

catalog:
  "ajv": "^8.17.1"
  "vite": "6.2.5"
  "vitest": "3.1.1"
  "svelte": "^5.25.9"
  "esm-env": "^1.2.2"
  "@sveltejs/kit": "^2.20.4"
  "@sveltejs/adapter-static": "^3.0.8"
  "@sveltejs/package": "^2.3.10"
  "@sveltejs/vite-plugin-svelte": "^5.0.3"
  "svelte-check": "^4.1.5"
  "@tsconfig/svelte": "^5.0.4"
  "@playwright/test": "^1.51.1"
  "@types/eslint": "^9.6.1"
  "autoprefixer": "^10.4.21"
  "eslint": "^9.24.0"
  "eslint-config-prettier": "^10.1.1"
  "eslint-plugin-svelte": "^3.5.1"
  "globals": "^16.0.0"
  "postcss": "^8.5.3"
  "prettier": "^3.5.3"
  "prettier-plugin-svelte": "^3.3.3"
  "tailwindcss": "^3.4.17"
  "typescript-eslint": "^8.29.1"
  "zod": "^3.24.2"
  "@tailwindcss/vite": "^4.1.3"

catalogs:
  next:
    "tailwindcss": "^4.1.3"